### ISSUE TITLE
'web-search.browser.styles'のデフォルト値CSSが構文誤り

### ISSUE THREAD

**Issue by fkfk** [nobuhito/atom-web-search#2]
'web-search.browser.styles'のデフォルト値としているCSS構文が誤っていたため、そのままでは動作していませんでした。
正しく解釈されるように修正してPR(#1)をしていますので、よろしければマージをお願いします。

**Comment by nobuhito** [comment]
@fkfk パッチありがとうございます！そのまま取り込ませていただきリリースしました :bow:
