### ISSUE TITLE
過去に作成したパネルオブジェクトが残り続けている

### ISSUE THREAD

**Issue by fkfk** [nobuhito/atom-web-search#4]
web-searchで検索をすればするほどパネルオブジェクトが生成され続け、前に作成したものは残ったままとなっているようです。
下の添付画像は4回検索を実施した時点でデベロッパーツールで確認したところです。

![モーダルパネル](https://bytebucket.org/from_kyushu/qiita_posts/raw/04e9eea789bdc9b86fd0c52ed0dfcda1d3dfc763/images/web_search_panel_objects_issue/modal_objects.jpg)

![右パネル](https://bytebucket.org/from_kyushu/qiita_posts/raw/04e9eea789bdc9b86fd0c52ed0dfcda1d3dfc763/images/web_search_panel_objects_issue/right_objects.jpg)

コードを確認すると`hide()`メソッドで非表示にしているだけでしたので、オブジェクトを再利用しないのであれば消してよいと判断し`destroy()`メソッドでオブジェクトを消すように修正してPR(#3)しています。
もし再利用を考えていらっしゃるのであればこの変更は逆に問題があるかと思いますので、その際はお手数ですがリジェクトしてください。

**Comment by fkfk** [comment]
再利用する方向で修正をいただいたようですのでこちらのIssueはcloseします。

**Comment by nobuhito** [comment]
@fkfk 何故か昨晩はこのIssueとPRが見えなくなっていまして、独自に対応してしまいました。
全然気づいていない場所だったので助かりました。情報ありがとうございました :bow:
